### ISSUE TITLE
[Bug] Wrong case on several directories and files.

### ISSUE THREAD

**Issue by pspierce** [creativetimofficial/ct-argon-dashboard-pro-svelte#1]
### Version
argon-dashboard 1.0
### Reproduction link
https://jsfiddle.net/qL3pjues/
### Operating System
linux ubuntu 20.04
### Device
desktop
### Browser & Version
chromium
### Steps to reproduce
Unzip argon-dashboard-pro-svelte-v1.0.0.zip
npm install
npm run dev
www-data@pimupgrade:~/pim/src/SvelteBundle/argon-dashboard-pro-svelte-v1.0.0$ npm run dev

> argon-dashboard-pro-svelte@1.0.0 dev /var/www/pim/src/SvelteBundle/argon-dashboard-pro-svelte-v1.0.0
> rollup -c -w

rollup v1.32.1
bundles src/main.js → public/build/bundle.js...
[!] Error: Could not resolve './views/dashboard/layout.svelte' from src/routes.js
Error: Could not resolve './views/dashboard/layout.svelte' from src/routes.js
    at error (/var/www/pim/src/SvelteBundle/argon-dashboard-pro-svelte-v1.0.0/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at ModuleLoader.handleResolveId (/var/www/pim/src/SvelteBundle/argon-dashboard-pro-svelte-v1.0.0/node_modules/rollup/dist/shared/node-entry.js:12410:24)
    at ModuleLoader.<anonymous> (/var/www/pim/src/SvelteBundle/argon-dashboard-pro-svelte-v1.0.0/node_modules/rollup/dist/shared/node-entry.js:12298:30)
    at Generator.next (<anonymous>)
    at fulfilled (/var/www/pim/src/SvelteBundle/argon-dashboard-pro-svelte-v1.0.0/node_modules/rollup/dist/shared/node-entry.js:38:28)

There are case-sensitivity issues throughout.  I changed dashboard to Dashboard through out routes.js but there are other issues.
### What is expected?
starts
### What is actually happening?
lots of errors due to misspelled files and directories.

---

**Comment by einazare** [comment]
Hello there, @pspierce 

Sorry for this late reply. The product was made by a third party that decided to not offer support, so Creative Tim just took the support for it.
To solve the issues you are having, please download and install [NodeJS LTS version](https://nodejs.org/en/), none of our products work with NodeJS (current) version due to our dependencies. We'll add this warning inside our live docs here in a few days when we'll release a new version of this product with updated dependencies as well.

Also, you will need to do the following:
```
npm i -E -D rollup-plugin-postcss postcss
```
After that, you need to go inside rollup.config.js and add inside the plugins array the following:
```
        postcss({
          extensions: [ '.css' ],
        }),
```
This will solve the rollup issues.
If you will have an error from google maps, you will also need to go inside `src/views/Dashboard/Maps/googleMaps.svelte` and replace 
```
import GoogleMapsLoader from "google-maps";
``` 
with 
```
import {Loader as GoogleMapsLoader} from "google-maps";
```

In a few days we'll release a new version of this product with the above fixes.

Best,
Manu
